# development/Dockerfile
FROM python:3.10

# 環境変数の設定 (Pythonが.pycファイルを生成しないようにし、Pythonがバッファリングしないようにする)
ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install poetry

COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# ソースコードをコンテナにコピー
COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
